"use client";

import { useEffect, useState } from "react";
import { cn } from "@/lib/utils";
import { moodVisuals } from "@/lib/pet/personality";
import type { MoodId } from "@/lib/pet/types";

const GRID = 24;
export const PET_GRID = GRID;

type Color =
  | "body"
  | "highlight"
  | "shadow"
  | "wing"
  | "outline"
  | "eye"
  | "comb"
  | "beak"
  | "leg"
  | "sparkle"
  | "dust";

type Pixel = readonly [x: number, y: number, c: Color];

type Frame = {
  pixels: Pixel[];
  // Anchor of the 'e' glyph; null for frames with baked closed eyes (sleep).
  eye: { x: number; y: number } | null;
};

const COLOR_VAR: Record<Color, string> = {
  body: "var(--pet-body)",
  highlight: "var(--pet-highlight)",
  shadow: "var(--pet-shadow)",
  wing: "var(--pet-wing)",
  outline: "var(--pet-outline)",
  eye: "var(--pet-outline)",
  comb: "var(--pet-comb)",
  beak: "var(--pet-beak)",
  leg: "var(--pet-leg)",
  sparkle: "var(--pet-sparkle)",
  dust: "var(--pet-dust)",
};

// Parse a 24-line, 24-char-wide string into a frame.
//  . = empty       B = body        H = highlight   S = belly shadow
//  W = wing/tail   O = outline (baked closed eye)  R = comb/wattle
//  Y = beak        L = leg (also dark lower beak)  e = eye (records anchor)
function parse(art: string): Frame {
  const map: Record<string, Color> = {
    O: "outline",
    B: "body",
    H: "highlight",
    S: "shadow",
    W: "wing",
    R: "comb",
    Y: "beak",
    L: "leg",
    e: "eye",
  };
  const pixels: Pixel[] = [];
  let eye: Frame["eye"] = null;
  const lines = art.split("\n").filter((l) => l.length > 0);
  if (process.env.NODE_ENV !== "production") {
    if (lines.length !== GRID) {
      throw new Error(`pet frame has ${lines.length} rows, want ${GRID}`);
    }
    lines.forEach((l, y) => {
      if (l.length !== GRID) {
        throw new Error(`pet frame row ${y} has ${l.length} chars, want ${GRID}`);
      }
    });
  }
  for (let y = 0; y < lines.length; y++) {
    const line = lines[y];
    for (let x = 0; x < line.length; x++) {
      const c = line[x];
      const color = map[c];
      if (!color) continue;
      pixels.push([x, y, color]);
      if (c === "e" && !eye) eye = { x, y };
    }
  }
  return { pixels, eye };
}

// --- Body frames ------------------------------------------------------------
//
// Authoring rules (all frames):
//  - exactly 24 lines x 24 chars, chicken faces right; scaleX(-1) mirrors it
//  - one plump Stardew-style blob: head merges straight into the body — no
//    neck gap, no oversized tail; just a small tail nub on the back
//  - grounded frames plant feet on rows 21-23 (toes on 23); airborne frames
//    tuck feet up around row 21 so the silhouette reads as flying
//  - keep the horizontal center of mass near x=11-12 so frame switches
//    within one action never jitter
//  - upright frames share the eye anchor (16,6); frames that move the head
//    move the 'e' glyph with it — the parser records it per frame
//  - sleep frames bake a closed eye ('OO') and omit 'e' so mood overlays
//    and blinking are skipped entirely

const FRAME_STAND = parse(`
........................
..............RR........
.............RRRR.......
............HBBBBB......
...........HBBBBBBB.....
...........BBBBBBBB.....
...........BBBBBeBBYY...
....BB....BBBBBBBBBY....
....BBB...BBBBBBBBR.....
.....BBBBBBBBBBBBBB.....
.....BBBBBBBBBBBBBBB....
....BBBBWWWWWBBBBBBB....
....BBBWWWWWWBBBBBBB....
....BBBBWWWWWBBBBBBB....
....BBBBBWWWBBBBBBBB....
....BSSSSSSSSSSBBBBB....
....BSSSSSSSSSBBBBBB....
.....BSSSSSSSSBBBBB.....
......BBBBBBBBBBBB......
.......BBBBBBBBBB.......
........BBBBBBBB........
..........LL..LL........
..........LL..LL........
.........LLL..LLL.......
`);

// Stride — legs apart front and back.
const FRAME_WALK_A = parse(`
........................
..............RR........
.............RRRR.......
............HBBBBB......
...........HBBBBBBB.....
...........BBBBBBBB.....
...........BBBBBeBBYY...
....BB....BBBBBBBBBY....
....BBB...BBBBBBBBR.....
.....BBBBBBBBBBBBBB.....
.....BBBBBBBBBBBBBBB....
....BBBBWWWWWBBBBBBB....
....BBBWWWWWWBBBBBBB....
....BBBBWWWWWBBBBBBB....
....BBBBBWWWBBBBBBBB....
....BSSSSSSSSSSBBBBB....
....BSSSSSSSSSBBBBBB....
.....BSSSSSSSSBBBBB.....
......BBBBBBBBBBBB......
.......BBBBBBBBBB.......
........BBBBBBBB........
.........LL....LL.......
.........LL....LL.......
........LLL....LLL......
`);

// Passing step — back foot planted, front foot lifted mid-swing.
const FRAME_WALK_B = parse(`
........................
..............RR........
.............RRRR.......
............HBBBBB......
...........HBBBBBBB.....
...........BBBBBBBB.....
...........BBBBBeBBYY...
....BB....BBBBBBBBBY....
....BBB...BBBBBBBBR.....
.....BBBBBBBBBBBBBB.....
.....BBBBBBBBBBBBBBB....
....BBBBWWWWWBBBBBBB....
....BBBWWWWWWBBBBBBB....
....BBBBWWWWWBBBBBBB....
....BBBBBWWWBBBBBBBB....
....BSSSSSSSSSSBBBBB....
....BSSSSSSSSSBBBBBB....
.....BSSSSSSSSBBBBB.....
......BBBBBBBBBBBB......
.......BBBBBBBBBB.......
........BBBBBBBB........
...........LL.LL........
...........LL.LLL.......
..........LLL...........
`);

// Drive — legs stretched into the stride.
const FRAME_RUN_A = parse(`
........................
..............RR........
.............RRRR.......
............HBBBBB......
...........HBBBBBBB.....
...........BBBBBBBB.....
...........BBBBBeBBYY...
....BB....BBBBBBBBBY....
....BBB...BBBBBBBBR.....
.....BBBBBBBBBBBBBB.....
.....BBBBBBBBBBBBBBB....
....BBBBWWWWWBBBBBBB....
....BBBWWWWWWBBBBBBB....
....BBBBWWWWWBBBBBBB....
....BBBBBWWWBBBBBBBB....
....BSSSSSSSSSSBBBBB....
....BSSSSSSSSSBBBBBB....
.....BSSSSSSSSBBBBB.....
......BBBBBBBBBBBB......
.......BBBBBBBBBB.......
........BBBBBBBB........
.........LL.....LL......
........LL.......LL.....
........LL.......LLL....
`);

// Contact — front foot planted under the chest, back leg folding up.
const FRAME_RUN_B = parse(`
........................
..............RR........
.............RRRR.......
............HBBBBB......
...........HBBBBBBB.....
...........BBBBBBBB.....
...........BBBBBeBBYY...
....BB....BBBBBBBBBY....
....BBB...BBBBBBBBR.....
.....BBBBBBBBBBBBBB.....
.....BBBBBBBBBBBBBBB....
....BBBBWWWWWBBBBBBB....
....BBBWWWWWWBBBBBBB....
....BBBBWWWWWBBBBBBB....
....BBBBBWWWBBBBBBBB....
....BSSSSSSSSSSBBBBB....
....BSSSSSSSSSBBBBBB....
.....BSSSSSSSSBBBBB.....
......BBBBBBBBBBBB......
.......BBBBBBBBBB.......
........BBBBBBBB........
...........LL..LL.......
............LL.LL.......
...............LLL......
`);

// Sleeping loaf — legs tucked away, body settled on the ground, eyes shut.
const FRAME_SLEEP_A = parse(`
........................
........................
........................
........................
........................
........................
........................
..............RR........
.............RRRR.......
............HBBBBB......
...........HBBBBBBB.....
...........BBBBOOBBYY...
....BB....BBBBBBBBBY....
....BBB...BBBBBBBBR.....
.....BBBBBBBBBBBBBB.....
.....BBBBBBBBBBBBBBB....
....BBBBWWWWWBBBBBBB....
....BBBWWWWWWBBBBBBB....
....BBBBWWWWWBBBBBBB....
....BSSSSSSSSSSBBBBB....
....BSSSSSSSSSBBBBBB....
.....BSSSSSSSSBBBBB.....
......BBBBBBBBBBBB......
.......SSSSSSSSSS.......
`);

// Exhale — the head settles 1px lower into the breast.
const FRAME_SLEEP_B = parse(`
........................
........................
........................
........................
........................
........................
........................
........................
..............RR........
.............RRRR.......
............HBBBBB......
...........HBBBBBBB.....
...........BBBBOOBBYY...
....BBB...BBBBBBBBBY....
.....BBBBBBBBBBBBBB.....
.....BBBBBBBBBBBBBBB....
....BBBBWWWWWBBBBBBB....
....BBBWWWWWWBBBBBBB....
....BBBBWWWWWBBBBBBB....
....BSSSSSSSSSSBBBBB....
....BSSSSSSSSSBBBBBB....
.....BSSSSSSSSBBBBB.....
......BBBBBBBBBBBB......
.......SSSSSSSSSS.......
`);

// Head dipped to chest height, beak angling down.
const FRAME_PECK_A = parse(`
........................
........................
........................
........................
...............RR.......
..............RRRR......
.............HBBBBB.....
....BB......HBBBBBBB....
....BBB.....BBBBBeBB....
.....BBBBBBBBBBBBBBB....
.....BBBBBBBBBBBBBBYY...
....BBBBWWWWWBBBBBBBY...
....BBBWWWWWWBBBBBBB....
....BBBBWWWWWBBBBBBB....
....BBBBBWWWBBBBBBBB....
....BSSSSSSSSSSBBBBB....
....BSSSSSSSSSBBBBBB....
.....BSSSSSSSSBBBBB.....
......BBBBBBBBBBBB......
.......BBBBBBBBBB.......
........BBBBBBBB........
..........LL..LL........
..........LL..LL........
.........LLL..LLL.......
`);

// Beak at the ground, tail up.
const FRAME_PECK_B = parse(`
........................
........................
........................
........................
........................
....BB..................
....BBB.................
.....BBB................
......BBBBBB............
.....BBBBBBBBBB.........
....BBBBBBBBBBBBB.......
....BBBBWWWWWBBBBB......
....BBBWWWWWWBBBBBB.....
....BBBBWWWWWBBBBBBB....
....BSSSSSSSSSBBBBBB....
....BSSSSSSSSSBBBBBBB...
.....BSSSSSSSSBBBBBBBR..
......BBBBBBBBBBBBeBBR..
.......BBBBBBBBBBBBBB...
........BBBBBBBBBBB.....
.........BBBBBBBBBBYY...
..........LL..LL........
..........LL..LL........
.........LLL..LLL.......
`);

// Wing raised over the back (standing stretch).
const FRAME_FLAP = parse(`
........................
..............RR........
.............RRRR.......
............HBBBBB......
...........HBBBBBBB.....
.......WWW.BBBBBBBB.....
......WWWW.BBBBBeBBYY...
....BBWWWWBBBBBBBBBY....
....BBBWWWBBBBBBBBR.....
.....BBBBBBBBBBBBBB.....
.....BBBBBBBBBBBBBBB....
....BBBBBBBBBBBBBBBB....
....BBBBBBBBBBBBBBBB....
....BBBBBBBBBBBBBBBB....
....BBBBBBBBBBBBBBBB....
....BSSSSSSSSSSBBBBB....
....BSSSSSSSSSBBBBBB....
.....BSSSSSSSSBBBBB.....
......BBBBBBBBBBBB......
.......BBBBBBBBBB.......
........BBBBBBBB........
..........LL..LL........
..........LL..LL........
.........LLL..LLL.......
`);

// Airborne, wings up, feet tucked.
const FRAME_FLY_A = parse(`
........................
..............RR........
.............RRRR.......
............HBBBBB......
...........HBBBBBBB.....
.......WWW.BBBBBBBB.....
......WWWW.BBBBBeBBYY...
....BBWWWWBBBBBBBBBY....
....BBBWWWBBBBBBBBR.....
.....BBBBBBBBBBBBBB.....
.....BBBBBBBBBBBBBBB....
....BBBBBBBBBBBBBBBB....
....BBBBBBBBBBBBBBBB....
....BBBBBBBBBBBBBBBB....
....BBBBBBBBBBBBBBBB....
....BSSSSSSSSSSBBBBB....
....BSSSSSSSSSBBBBBB....
.....BSSSSSSSSBBBBB.....
......BBBBBBBBBBBB......
.......BBBBBBBBBB.......
........BBBBBBBB........
...........LLL..........
........................
........................
`);

// Airborne, wings swept down past the belly.
const FRAME_FLY_B = parse(`
........................
..............RR........
.............RRRR.......
............HBBBBB......
...........HBBBBBBB.....
...........BBBBBBBB.....
...........BBBBBeBBYY...
....BB....BBBBBBBBBY....
....BBB...BBBBBBBBR.....
.....BBBBBBBBBBBBBB.....
.....BBBBBBBBBBBBBBB....
....BBBBBBBBBBBBBBBB....
....BBBBBBBBBBBBBBBB....
....BBBBBBBBBBBBBBBB....
....BBBBBBBBBBBBBBBB....
...WWWWWWSSSSSSBBBBB....
..WWWWWSSSSSSSBBBBBB....
.WWWWBSSSSSSSSBBBBB.....
......BBBBBBBBBBBB......
.......BBBBBBBBBB.......
........BBBBBBBB........
...........LLL..........
........................
........................
`);

// Airborne, wing spread flat behind — descending glide.
const FRAME_GLIDE = parse(`
........................
..............RR........
.............RRRR.......
............HBBBBB......
...........HBBBBBBB.....
...........BBBBBBBB.....
...........BBBBBeBBYY...
....BB....BBBBBBBBBY....
....BBB...BBBBBBBBR.....
.....BBBBBBBBBBBBBB.....
.....BBBBBBBBBBBBBBB....
....BBBBBBBBBBBBBBBB....
.WWWWWWWWWWWWBBBBBBB....
..WWWWWWWWWWWBBBBBBB....
....BBBBBBBBBBBBBBBB....
....BSSSSSSSSSSBBBBB....
....BSSSSSSSSSBBBBBB....
.....BSSSSSSSSBBBBB.....
......BBBBBBBBBBBB......
.......BBBBBBBBBB.......
........BBBBBBBB........
...........LLL..........
........................
........................
`);

// --- Actions ----------------------------------------------------------------

export type PetAction =
  | "stand"
  | "walk"
  | "run"
  | "fly"
  | "glide"
  | "peck"
  | "flap"
  | "sleep";

const SEQUENCES: Record<PetAction, { frames: Frame[]; ms: number }> = {
  stand: { frames: [FRAME_STAND], ms: 0 },
  walk: { frames: [FRAME_WALK_A, FRAME_WALK_B], ms: 180 },
  run: { frames: [FRAME_RUN_A, FRAME_RUN_B], ms: 110 },
  fly: { frames: [FRAME_FLY_A, FRAME_FLY_B], ms: 140 },
  glide: { frames: [FRAME_GLIDE], ms: 0 },
  peck: {
    frames: [FRAME_PECK_A, FRAME_PECK_B, FRAME_PECK_B, FRAME_PECK_A],
    ms: 130,
  },
  flap: { frames: [FRAME_FLAP, FRAME_STAND], ms: 160 },
  sleep: { frames: [FRAME_SLEEP_A, FRAME_SLEEP_B], ms: 1200 },
};

// How long one-shot idle behaviors run before reverting to stand.
const MICRO_MS: Record<"peck" | "flap", number> = {
  peck: 4 * 130 * 2, // two peck loops
  flap: 2 * 160 * 3, // three wing stretches
};

// --- Mood eye overrides -------------------------------------------------------

// Offsets are relative to the current frame's eye anchor, so mood eyes track
// the head through peck frames. dx is toward the tail (-) / beak (+).
function eyeOverlay(
  mood: MoodId,
  blink: boolean,
): { hide: boolean; add: readonly (readonly [number, number])[] } {
  // Blink overrides everything except moods whose eyes are already closed.
  if (blink && mood !== "celebrating" && mood !== "proud" && mood !== "sleepy") {
    return { hide: true, add: [[-1, 0], [0, 0]] };
  }

  switch (mood) {
    case "urgent":
      // Wide alert eye — 2 pixels stacked.
      return { hide: false, add: [[0, -1]] };
    case "focused":
      // Concentrated narrow eye.
      return { hide: true, add: [[-1, 0], [0, 0]] };
    case "celebrating":
      // Closed happy arc ^_^
      return { hide: true, add: [[-1, 1], [0, 0], [1, 1]] };
    case "proud":
      // Smug half-lidded eye.
      return { hide: true, add: [[-1, 0], [0, -1]] };
    case "chilling":
      // Half-closed — lower lid only.
      return { hide: true, add: [[-1, 1], [0, 1]] };
    case "sleepy":
    case "disappointed":
      // Closed — low horizontal dash.
      return { hide: true, add: [[-1, 1], [0, 1], [1, 1]] };
    case "worried":
      // Squinted small eye.
      return { hide: true, add: [[0, 0]] };
    default:
      // nudging / comeback — default open eye.
      return { hide: false, add: [] };
  }
}

// --- Particles ----------------------------------------------------------------

export type PetEffect = { kind: "dust" | "feather"; key: number } | null;

function ParticleLayer({
  mood,
  action,
  effect,
  animate,
}: {
  mood: MoodId;
  action: PetAction;
  effect: PetEffect;
  animate: boolean;
}) {
  const visuals = moodVisuals(mood);
  return (
    <>
      {visuals.particle === "zzz" && (
        <g className={animate ? "pet-particle-zzz" : undefined}>
          <rect x={19} y={4} width={1} height={1} fill="var(--pet-outline)" />
          <rect x={21} y={2} width={1} height={1} fill="var(--pet-outline)" />
        </g>
      )}
      {visuals.particle === "sparkle" && (
        <g className={animate ? "pet-particle-sparkle" : undefined}>
          <rect x={3} y={4} width={1} height={1} fill="var(--pet-sparkle)" />
          <rect x={21} y={7} width={1} height={1} fill="var(--pet-sparkle)" />
          <rect x={2} y={13} width={1} height={1} fill="var(--pet-sparkle)" />
          <rect x={22} y={16} width={1} height={1} fill="var(--pet-sparkle)" />
        </g>
      )}
      {visuals.particle === "sweat" && (
        <g>
          <rect x={21} y={4} width={1} height={1} fill="var(--pet-beak)" />
          <rect x={22} y={5} width={1} height={1} fill="var(--pet-beak)" />
        </g>
      )}
      {animate && action === "run" && (
        <g className="pet-particle-dust-loop">
          <rect x={5} y={22} width={1} height={1} fill="var(--pet-dust)" />
          <rect x={3} y={23} width={1} height={1} fill="var(--pet-dust)" />
          <rect x={7} y={23} width={1} height={1} fill="var(--pet-dust)" />
        </g>
      )}
      {animate && effect?.kind === "dust" && (
        <g key={`fx-${effect.key}`} className="pet-particle-dust">
          <rect x={8} y={21} width={1} height={1} fill="var(--pet-dust)" />
          <rect x={10} y={22} width={1} height={1} fill="var(--pet-dust)" />
          <rect x={13} y={21} width={1} height={1} fill="var(--pet-dust)" />
          <rect x={15} y={22} width={1} height={1} fill="var(--pet-dust)" />
          <rect x={11} y={20} width={1} height={1} fill="var(--pet-dust)" />
        </g>
      )}
      {animate && effect?.kind === "feather" && (
        <g key={`fx-${effect.key}`} className="pet-particle-feather">
          <rect x={5} y={8} width={1} height={1} fill="var(--pet-wing)" />
          <rect x={6} y={9} width={1} height={1} fill="var(--pet-wing)" />
        </g>
      )}
    </>
  );
}

// --- Component ------------------------------------------------------------

export type PetSpriteProps = {
  mood: MoodId;
  facing?: "left" | "right";
  action?: PetAction;
  /** Enables occasional peck/flap micro-behaviors while standing. */
  idle?: boolean;
  /** false = fully static frame (PNG export, reduced motion). */
  animate?: boolean;
  /** One-shot particle burst; bump `key` to replay. */
  effect?: PetEffect;
  pixelSize?: number;
  className?: string;
};

export function PetSprite({
  mood,
  facing = "right",
  action = "stand",
  idle = false,
  animate = true,
  effect = null,
  pixelSize = 3,
  className,
}: PetSpriteProps) {
  const [frameIndex, setFrameIndex] = useState(0);
  const [blink, setBlink] = useState(false);
  const [microAction, setMicroAction] = useState<"peck" | "flap" | null>(null);

  // Idle micro-behaviors only apply while plainly standing.
  const effective: PetAction =
    action === "stand" && microAction ? microAction : action;

  // Frame cycling for the current action.
  useEffect(() => {
    setFrameIndex(0);
    const seq = SEQUENCES[effective];
    if (!animate || seq.frames.length <= 1) return;
    const interval = window.setInterval(
      () => setFrameIndex((i) => (i + 1) % seq.frames.length),
      seq.ms,
    );
    return () => window.clearInterval(interval);
  }, [effective, animate]);

  // Slow random blink.
  useEffect(() => {
    if (!animate) return;
    let cancelled = false;
    const schedule = () => {
      const next = 4000 + Math.random() * 3500;
      window.setTimeout(() => {
        if (cancelled) return;
        setBlink(true);
        window.setTimeout(() => {
          if (cancelled) return;
          setBlink(false);
          schedule();
        }, 140);
      }, next);
    };
    schedule();
    return () => {
      cancelled = true;
    };
  }, [animate]);

  // Occasional peck or wing stretch while idling.
  useEffect(() => {
    setMicroAction(null);
    if (!idle || !animate || action !== "stand") return;
    let cancelled = false;
    let clearTimer: number | undefined;
    const schedule = () => {
      const next = 5000 + Math.random() * 5000;
      window.setTimeout(() => {
        if (cancelled) return;
        const pick = Math.random() < 0.6 ? "peck" : "flap";
        setMicroAction(pick);
        clearTimer = window.setTimeout(() => {
          if (cancelled) return;
          setMicroAction(null);
          schedule();
        }, MICRO_MS[pick]);
      }, next);
    };
    schedule();
    return () => {
      cancelled = true;
      if (clearTimer) window.clearTimeout(clearTimer);
    };
  }, [idle, animate, action]);

  const seq = SEQUENCES[effective];
  const frame = seq.frames[frameIndex % seq.frames.length];

  // Mood/blink eye overlay, anchored to this frame's eye.
  let pixels: readonly Pixel[] = frame.pixels;
  if (frame.eye) {
    const overlay = eyeOverlay(mood, blink && animate);
    if (overlay.hide) pixels = pixels.filter((p) => p[2] !== "eye");
    if (overlay.add.length > 0) {
      const { x, y } = frame.eye;
      pixels = [
        ...pixels,
        ...overlay.add.map(
          ([dx, dy]) => [x + dx, y + dy, "eye"] as const,
        ),
      ];
    }
  }

  // Warm Stardew-ish palette. Sparkle is gold on purpose — the theme accent
  // is green and reads as a glitch on the cream body, never use it here.
  const cssVars: React.CSSProperties = {
    // @ts-expect-error CSS custom properties
    "--pet-body": "#f9f3e6",
    "--pet-highlight": "#fffdf5",
    "--pet-shadow": "#e6d9ba",
    "--pet-wing": "#ddcda6",
    "--pet-outline": "#221a14",
    "--pet-comb": "#d94545",
    "--pet-beak": "#e8a01c",
    "--pet-leg": "#c8801a",
    "--pet-sparkle": "#f2c94c",
    "--pet-dust": "#d8cdb2",
  };

  return (
    <div
      className={cn("inline-block image-pixelated", className)}
      style={{
        width: GRID * pixelSize,
        height: GRID * pixelSize,
        ...cssVars,
      }}
      aria-label={`pet chicken: ${mood}`}
      role="img"
    >
      <div
        style={{
          width: "100%",
          height: "100%",
          transform: facing === "left" ? "scaleX(-1)" : undefined,
          transformOrigin: "center",
        }}
      >
        <svg
          viewBox={`0 0 ${GRID} ${GRID}`}
          width="100%"
          height="100%"
          shapeRendering="crispEdges"
          style={{ display: "block" }}
        >
          {pixels.map(([x, y, c], i) => (
            <rect
              key={`${i}-${x}-${y}`}
              x={x}
              y={y}
              width={1}
              height={1}
              fill={COLOR_VAR[c]}
            />
          ))}
          <ParticleLayer
            mood={mood}
            action={effective}
            effect={effect}
            animate={animate}
          />
        </svg>
      </div>
    </div>
  );
}
